// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class movies_display_model_attibute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movies_display_model_attibute));
        
        string IMigrationMetadata.Id
        {
            get { return "201705241128234_movies_display_model_attibute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
