// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_movie_model_validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_movie_model_validation));
        
        string IMigrationMetadata.Id
        {
            get { return "201705261240314_update_movie_model_validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
